version: "3.7"
services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    environment:
      # htpasswd auth:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      # tls config:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /certs/privkey.pem
      VIRTUAL_HOST: example-server/ip.com
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: example-letsencrypt.com
      LETSENCRYPT_EMAIL: my-email@host.com
    volumes:
      - /home/ben/storage/registry:/var/lib/registry
      - /etc/letsencrypt/archive/example-server.com/:/certs
      - /home/ben/docker-registry-config/registry/auth:/auth
networks:
  default:
    external:
      name: letsencrypt
